apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sampleginx
  name: sampleginx
  annotations:
    state: testing
    flux: fluxing
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sampleginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

