apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sampleginx
  name: sampleginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sampleginx
status:
  loadBalancer: {}

